# Generated by Django 2.2.6 on 2019-10-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='remoteFiles',
        ),
    ]
