# Generated by Django 2.2.6 on 2019-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_remotefiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='key',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='key',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
