# Generated by Django 2.2.6 on 2019-11-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191101_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
